version: "3.7"
services:
  clair-db:
    container_name: clair-db
    image: postgres:12.1
    environment:
      POSTGRES_USER: "clair"
      POSTGRES_DB: "clair"
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U clair -d clair"]
      interval: 10s
      timeout: 9s
      retries: 3
      start_period: 10s

